parameters:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_recaptcha_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET_KEY)%'
    uploads_directory: '%kernel.project_dir%/public/uploads'

# config/services.yaml
services:
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les services (ex: Commandes, Événements, etc.)
        bind:
            $kernel.projectDir: '%kernel.project_dir%'

    # Déclaration de tous les services du namespace App\ automatiquement
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Ajout explicite de l'extension Twig des catégories
    App\Twig\GlobalCategoriesExtension:
        tags: ['twig.extension']

    App\Service\RecaptchaService:
        arguments:
            $secretKey: '%google_recaptcha_secret_key%'

    App\Twig\RecaptchaExtension:
        arguments:
            $siteKey: '%google_recaptcha_site_key%'
        tags: ['twig.extension']
